{{- if and .Values.ssl.selfsignedCA.enabled .Values.ssl.selfsignedCA.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ssl.selfsignedCA.secretName }}
  namespace: cert-manager
spec:
  commonName: Self-Signed CA
  secretName: {{ .Values.ssl.selfsignedCA.secretName }}
  isCA: true
  issuerRef:
    name: {{ .Values.ssl.selfsignedCA.name }}
    kind: ClusterIssuer
{{- end }}
