apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}-discovery
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 7800
      targetPort: 7800
      protocol: TCP
      name: jgroups-bind
    - port: 57800
      targetPort: 57800
      protocol: TCP
      name: jgroups-fd
