apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ index .Values.service "http-port" }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.ssl.enabled }}
    - port: {{ index .Values.service "https-port" }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
