namespace: ""
nameOverride: ""
fullnameOverride: ""

environmentVariables:
  configMap:
    configMapName: keycloak-env
    configMapValues:
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HEALTH_ENABLED: "true"
      KC_CACHE: ispn
      ADDITIONAL_JAVA_OPTS: ""
      PROXY_ADDRESS_FORWARDING: "true"
  secret:
    secretName: keycloak-secret-env

ssl:
  enabled: true
  secret:
    secretName: example.com-tls

reloader:
  enableAnnotations: false

statefulset:
  replicaCount: 2
  image:
    repository: "quay.io/keycloak/keycloak"
    tag: ""
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  containerArgs: start
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  # securityContext:
  #   capabilities:
  #     drop:
  #     - ALL
  #   runAsNonRoot: true
  #   runAsUser: 1000
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /health/live
      port: 9000
      scheme: HTTP
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /health/ready
      port: 9000
      scheme: HTTP
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  startupProbe:
    failureThreshold: 600
    httpGet:
      path: /health/started
      port: 9000
      scheme: HTTP
    periodSeconds: 1
    successThreshold: 1
    timeoutSeconds: 1
  resources: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: 1000Mi
  #   requests:
  #     cpu: 500m
  #     memory: 500Mi

persistence:
  enabled: false
  type: pvc
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  selectorLabels: {}

service:
  type: ClusterIP
  http-port: 80
  https-port: 443

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
  hosts:
    - host: auth.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: example.com-tls
      hosts:
        - auth.example.com

autoscaling:
  enabled: false 
  minReplicas: 2 
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
