{{- if and .Values.ssl.selfsignedCA.enabled .Values.ssl.selfsignedCA.create }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ssl.selfsignedCA.name }}
spec:
  selfSigned: {}
{{- end }}
