apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.environmentVariables.configMap.configMapName }}
  namespace: {{ .Values.namespace }}
data:
  {{- if .Values.ssl.enabled }}
  LDAP_ENABLE_TLS: 'yes'
  LDAP_TLS_CERT_FILE: "/opt/openldap/ssl/tls.crt"
  LDAP_TLS_KEY_FILE: "/opt/openldap/ssl/tls.key"
  LDAP_TLS_CA_FILE: "/opt/openldap/ssl/fullchain.crt"
  {{- else }}
  LDAP_ENABLE_TLS: 'no'
  {{- end }}
{{ toYaml .Values.environmentVariables.configMap.configMapValues | indent 2 }}
